{{- $workloadType := .Values.workloadType | default "Deployment" }}
{{- $timezone := "Asia/Ho_Chi_Minh" }}
{{- if and (hasKey .Values "global") (hasKey .Values.global "timezone") }}
{{- $timezone = .Values.global.timezone }}
{{- end }}
apiVersion: apps/v1
kind: {{ $workloadType }}
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- if eq $workloadType "StatefulSet" }}
  serviceName: {{ .Chart.Name }}-headless
  {{- end }}
  {{- if and (ne $workloadType "DaemonSet") (not .Values.autoscaling.enabled) }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  {{- if and (eq $workloadType "Deployment") .Values.strategy }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  {{- end }}
  {{- if and (or (eq $workloadType "StatefulSet") (eq $workloadType "DaemonSet")) .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      imagePullSecrets: {{ include "common.imagePullSecrets" . | indent 8 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if ne $workloadType "DaemonSet" }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- else -}}
      {{/* Default Affinities is soft podAntiAffinity. */}}
      {{- include "common.affinities" (dict "context" $) | nindent 6 }}
      {{/* Use the following to set specific affinities if needed */}}
      {{/*
      {{- include "common.affinities" (dict "pod" (dict "type" "hard" "name" "FOO") "context" $) | nindent 6 }}
      {{- include "common.affinities" (dict "pod" (dict "type" "soft" "name" "FOO") "context" $) | nindent 6 }}
      {{- include "common.affinities" (dict "podAnti" (dict "type" "hard" "name" "FOO") "context" $) | nindent 6 }}
      {{- include "common.affinities" (dict "podAnti" (dict "type" "soft" "name" "FOO") "context" $) | nindent 6 }}
      {{- include "common.affinities" (dict "node" (dict "type" "hard" "key" "FOO" "values" (list "BAR" "BAZ")) "context" $) | nindent 6 }}
      {{- include "common.affinities" (dict "node" (dict "type" "soft" "key" "FOO" "values" (list "BAR" "BAZ")) "context" $) | nindent 6 }}
      */}}
      {{- end -}}
      {{- end -}}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end -}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "common.image" . }}
          {{- if .Values.image.pullSecret }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- end }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          env:
            - name: TZ
              value: {{ default $timezone | quote }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- /* unshareVolume(volumeMount): define in the chart's values.yaml */ -}}
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
      volumes:
      {{- /* unshareVolume(volume): define in the chart's values.yaml */ -}}
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}